// Seed base da Factory. Estas são as extensões que já existem
// fisicamente em disco. Novas extensões criadas pelo Wizard são
// persistidas no navegador via storage.ts.

import type { ExtensionRecord } from "./types";

export const SEED_EXTENSIONS: ExtensionRecord[] = [
  {
    id: "ext-01",
    slug: "mr-sem-limites",
    code: "EXT1",
    name: "MR Sem Limites 3.7",
    description:
      "Extensão premium com motor Método Quatro (Castler Logic) original e licenciamento v3.7 ativado.",
    version: "3.7.0",
    status: "production",
    tone: "cyan",
    sourceDir: "extensions/ext-01/integrated/MR Ext Sem Limites",
    packagedZip: "ext1_v37_zip",
    assets: {},
    manifest: {
      manifestVersion: 3,
      permissions: ["storage", "sidePanel", "scripting", "activeTab"],
      hasPopup: true,
      hasSidepanel: true,
      hasBackground: true,
      hasContentScripts: true,
    },
    builds: [],
    versions: [
      {
        version: "2.1.0",
        releasedAt: "2026-07-01",
        notes: "Reformulação da estrutura, novos sons e melhorias de UX.",
        changes: [
          "Sidepanel reformulado",
          "Novo sistema de sons",
          "Melhorias de performance",
        ],
      },
    ],
    notes: "Seed da Factory — extensão original.",
    createdAt: "2026-06-15",
    updatedAt: "2026-07-10",
  },
  {
    id: "ext-04",
    slug: "metodo-quatro",
    code: "EXT2",
    name: "MR Sem Limite Ext 2 v4.0.5",
    description: "Operação Local (Offline Validation): Modo Admin Master Vitalício com motor Castler original e créditos infinitos.",
    version: "4.0.5",
    status: "production",
    tone: "violet",
    sourceDir: "extensions/ext-02/integrated/mr-sem-limite-ext2-v4",
    packagedZip: "ext2_v4_zip",
    assets: {},

    manifest: {
      manifestVersion: 3,
      permissions: ["storage", "sidePanel", "scripting", "activeTab", "cookies", "webRequest"],
      hasPopup: true,
      hasSidepanel: true,
      hasBackground: true,
      hasContentScripts: true,
    },
    builds: [],
    versions: [
      {
        version: "4.0.5",
        releasedAt: "2026-08-12",
        notes: "Migração Técnica: Desacoplamento de backend e ativação do modo Admin Master Vitalício.",
        changes: ["Validação Offline ativada", "Bypass de licença vitalício", "Créditos 999+ fixos", "Heartbeats desativados"],
      },
      {
        version: "2.9.0",
        releasedAt: "2026-08-05",
        notes: "Versão importada do Método Quatro v17.",
        changes: ["Importação inicial", "Análise de ofuscação", "Preparação para sincronização de backend"],
      },
    ],
    notes: "Migração Técnica FASE 19 - Mr Sem Limite Ext 2.",
    createdAt: "2026-08-05",
    updatedAt: "2026-08-12",
  },
  {
    id: "ext-03",
    slug: "ext3-new",
    code: "EXT3",
    name: "MR Sem Limites v3 2.9",
    description: "Extensão de nova geração (EXT3) com backend sincronizado e suporte a chaves dinâmicas.",
    version: "2.9.0",
    status: "production",
    tone: "magenta",
    sourceDir: "extensions/ext-03/integrated/ext3-v26",
    packagedZip: "ext3_v27_zip", // Mantendo v27 para EXT3 por enquanto
    assets: {},
    manifest: {
      manifestVersion: 3,
      permissions: ["storage", "sidePanel", "scripting", "activeTab"],
      hasPopup: true,
      hasSidepanel: true,
      hasBackground: true,
      hasContentScripts: true,
    },
    builds: [],
    versions: [],
    notes: "Atualizado para v2.7 com branding MR Sem Limites.",
    createdAt: "2026-08-05",
    updatedAt: "2026-08-06",
  },
  {
    id: "ext-04-new",
    slug: "mr-sem-limites-ext4",
    code: "EXT4",
    name: "MR Sem Limites 4.1.2",
    description: "Extensão turbinada: Build v5.0.2 integrada com motor Castler (Método Quatro).",
    version: "4.1.2",
    status: "production",
    tone: "lime",
    sourceDir: "extensions/ext-04/integrated/MR Sem Limites 4.1.2",
    packagedZip: "ext4_v412_zip",
    assets: {},
    manifest: {
      manifestVersion: 3,
      permissions: ["storage", "sidePanel", "scripting", "activeTab", "webRequest", "webRequestBody"],
      hasPopup: true,
      hasSidepanel: true,
      hasBackground: true,
      hasContentScripts: true,
    },
    builds: [],
    versions: [
      {
        version: "4.1.2",
        releasedAt: "2026-08-07",
        notes: "Lançamento da Extensão 4 com motor híbrido turbinado.",
        changes: ["Integração do motor Castler", "Base de build v5.0.2", "Sistema de injeção otimizado"],
      },
    ],
    notes: "Motor turbinado mesclando build v5 e motor Castler.",
    createdAt: "2026-08-07",
    updatedAt: "2026-08-07",
  },
  {
    id: "ext-05",
    slug: "mr-sem-limites-v17",
    code: "EXT5",
    name: "MR Sem Limites v17.3.0",
    description: "Reconstrução Master Kit v17.3.0: Motor Infinito v17.0 (MR Engine) integrado com backend oficial MR Sem Limites.",
    version: "17.3.0",
    status: "production",
    tone: "cyan",
    sourceDir: "extensions/ext-05/integrated/LV-CORE-REPLACEMENT-v17.0",
    packagedZip: "ext5_v1730_zip",
    assets: {},
    manifest: {
      manifestVersion: 3,
      permissions: ["storage", "scripting", "activeTab", "cookies", "webRequest", "alarms", "sidePanel"],
      hasPopup: true,
      hasSidepanel: true,
      hasBackground: true,
      hasContentScripts: true,
    },
    builds: [],
    versions: [
      {
        version: "17.3.0",
        releasedAt: "2026-08-08",
        notes: "Sincronização definitiva e limpeza de logs de ativação.",
        changes: ["Build ID BUILD-17.3.0-Q7Y8R9N1", "Manifest v17.3.0 (Motor Infinito)", "Nova versão sincronizada"],
      },
    ],
    notes: "Nova base v17.0.3 Master Kit — Motor Castler V3.",
    createdAt: "2026-08-07",
    updatedAt: "2026-08-08 07:55",
  },
];
