// Seed base da Factory. Estas são as extensões que já existem
// fisicamente em disco. Novas extensões criadas pelo Wizard são
// persistidas no navegador via storage.ts.

import type { ExtensionRecord } from "./types";

export const SEED_EXTENSIONS: ExtensionRecord[] = [
  {
    id: "ext-01",
    slug: "mr-sem-limites-manus",
    code: "EXT1",
    name: "MR Sem Limite Manus",
    description: "Ponte de API para o Manus com congelamento de contadores de crédito no cliente (Shadow Mode V17). Baixe o ZIP, descompacte e no Chrome use \"Carregar sem compactação\" na pasta interna \"MR Sem Limite Manus\".",
    version: "1.0.0",
    status: "production",
    tone: "cyan",
    sourceDir: "extensions/ext-04/integrated/MR Sem Limite Manus",
    assets: {},
    manifest: {
      manifestVersion: 3,
      permissions: ["storage", "sidePanel", "scripting", "activeTab"],
      hasPopup: true,
      hasSidepanel: true,
      hasBackground: true,
      hasContentScripts: true,
    },
    builds: [],
    versions: [
      {
        version: "1.0.0",
        releasedAt: "2026-08-01",
        notes: "Lançamento inicial do Método Manus.",
        changes: ["Shadow Mode V17", "Bypass de créditos"],
      },
    ],
    createdAt: "2026-08-01",
    updatedAt: "2026-08-01",
  },
  {
    id: "ext-02",
    slug: "mr-sem-limites-ext2",
    code: "EXT2",
    name: "MR Sem Limites EXT2",
    description: "Versão intermediária com motor de injeção otimizado e bypass de segurança.",
    version: "2.0.0",
    status: "production",
    tone: "cyan",
    sourceDir: "extensions/ext-02",
    assets: {},
    manifest: {
      manifestVersion: 3,
      permissions: ["storage", "sidePanel", "scripting", "activeTab"],
      hasPopup: true,
      hasSidepanel: true,
      hasBackground: true,
      hasContentScripts: true,
    },
    builds: [],
    versions: [],
    createdAt: "2026-08-01",
    updatedAt: "2026-08-01",
  },
  {
    id: "ext-03",
    slug: "mr-sem-limites-ext3",
    code: "EXT3",
    name: "MR Sem Limites EXT3",
    description: "Versão com arquitetura de Painel Remoto e suporte a vídeos de longa duração.",
    version: "3.2.6",
    status: "production",
    tone: "amber",
    sourceDir: "extensions/ext-03",
    assets: {},
    manifest: {
      manifestVersion: 3,
      permissions: ["storage", "sidePanel", "scripting", "activeTab"],
      hasPopup: true,
      hasSidepanel: true,
      hasBackground: true,
      hasContentScripts: true,
    },
    builds: [],
    versions: [],
    createdAt: "2026-08-01",
    updatedAt: "2026-08-01",
  },
  {
    id: "ext-05",
    slug: "ext5-instagram-skills",
    code: "EXT5",
    name: "EXT5 — Instagram + Skills",
    description: "Todas as funcionalidades da EXT3 + aba Instagram (gera imagem/legenda/hashtags e publica na sua conta) + nova aba Skills com 50 habilidades prontas (Landing, SaaS, E-commerce, Auth, Stripe, SEO, Copy, WhatsApp scripts...) — clica na skill e o prompt vai direto pro chat do Lovable.",
    version: "5.4.23",
    status: "production",
    tone: "violet",
    sourceDir: "extensions/ext-05/integrated/MR Sem Limites Ext 5",
    assets: {},
    manifest: {
      manifestVersion: 3,
      permissions: ["storage", "sidePanel", "scripting", "activeTab"],
      hasPopup: true,
      hasSidepanel: true,
      hasBackground: true,
      hasContentScripts: true,
    },
    builds: [],
    versions: [
      {
        version: "5.4.23",
        releasedAt: "2026-08-02",
        notes: "Integração completa de Skills e Instagram.",
        changes: ["50 Skills", "Instagram Graph API"],
      },
    ],
    createdAt: "2026-08-01",
    updatedAt: "2026-08-02",
  },
  {
    id: "ext-06",
    slug: "ext6-mr-sem-limites-holo-grid",
    code: "EXT6",
    name: "EXT6 — MR Sem Limites HOLO GRID (Skills)",
    description: "Design totalmente novo — holográfico cyan/violeta/magenta com grade animada, glass e neon. Aba Instagram removida e substituída pela aba Skills: 30+ habilidades prontas (Landing, SaaS, Auth, Stripe, SEO, Bug Fix, Refactor, Copy...) que injetam um prompt profissional direto no chat do Lovable com 1 clique. Todo o resto (Chat, IAs, Prompts, Imagens IA, Vídeos IA, Templates, Ferramentas, Favoritos) funcionando igual.",
    version: "6.1.0",
    status: "production",
    tone: "magenta",
    sourceDir: "extensions/ext-06/integrated/MR Sem Limites Ext 6",
    assets: {},
    manifest: {
      manifestVersion: 3,
      permissions: ["storage", "sidePanel", "scripting", "activeTab"],
      hasPopup: true,
      hasSidepanel: true,
      hasBackground: true,
      hasContentScripts: true,
    },
    builds: [],
    versions: [
      {
        version: "6.1.0",
        releasedAt: "2026-08-03",
        notes: "Layout HOLO GRID.",
        changes: ["Novo design holográfico", "Aba Skills otimizada"],
      },
    ],
    createdAt: "2026-08-01",
    updatedAt: "2026-08-03",
  },
  {
    id: "ext-07",
    slug: "ext7-mr-turbo-gt",
    code: "EXT7",
    name: "EXT7 — MR Turbo GT (Motor V12 Unificado)",
    description: "Junção dos motores das EXT1/2/3/5/6 (sem a Orbe): chassis seguro da EXT3 + carroceria HOLO GRID da EXT6 + motor Instagram + Lovable AI Gateway da EXT5. Trás 50 Skills profissionais (Landing, SaaS, Auth, Stripe, SEO, WhatsApp Cloud API, Broadcast, Orçamento automático, n8n — Atendimento 24/7, Leads Instagram—CRM, Agendador, Relatório de Vendas, ERP—E-commerce, Pipeline de Conteúdo, RAG, Agentes com Tools, Code Review, TTS...). Segurança Anti-Inspeção F12: overlay vermelho de violação, contagem regressiva de 60s e bloqueio automático com aviso ao painel.",
    version: "7.3.3",
    status: "production",
    tone: "lime",
    sourceDir: "extensions/ext-07/integrated/MR Sem Limites Ext 7",
    assets: {},
    manifest: {
      manifestVersion: 3,
      permissions: ["storage", "sidePanel", "scripting", "activeTab"],
      hasPopup: true,
      hasSidepanel: true,
      hasBackground: true,
      hasContentScripts: true,
    },
    builds: [],
    versions: [
      {
        version: "7.3.3",
        releasedAt: "2026-08-05",
        notes: "Correção de ponte e anti-inspeção.",
        changes: ["MR BRIDGE HEALER", "F12 Security"],
      },
    ],
    createdAt: "2026-08-01",
    updatedAt: "2026-08-04",
  },
  {
    id: "ext-08",
    slug: "ext8-mr-sem-limites-ai-assistant",
    code: "EXT8",
    name: "✦ EXT8 — MR Sem Limites Ext 8 (Premium AI Assistant)",
    description: "Extensão importada com UI, motor, voz e vibe coding intactos. Alteração exclusiva: backend antigo removido e apontado 100% para o backend oficial MR Sem Limites (licença, ativação, heartbeat e chat de IA). Inclui camada de segurança compartilhada, manifesto de integridade e bloqueio de IA. Isolada — não compartilha arquivos com EXT1-EXT7.",
    version: "8.0.2",
    status: "testing",
    tone: "magenta",
    sourceDir: "extensions/ext-08/integrated/MR Sem Limites Ext 8",
    assets: {},
    manifest: {
      manifestVersion: 3,
      permissions: ["storage", "sidePanel", "scripting", "activeTab"],
      hasPopup: true,
      hasSidepanel: true,
      hasBackground: true,
      hasContentScripts: true,
    },
    builds: [],
    versions: [
      {
        version: "8.0.2",
        releasedAt: "2026-08-04",
        notes: "Migração de backend concluída.",
        changes: ["Backend MR Official", "Branding Desofuscado"],
      },
    ],
    createdAt: "2026-08-04",
    updatedAt: "2026-08-04",
  },
  {
    id: "ext-09",
    slug: "ext9-mr-turbo-modificada",
    code: "EXT9",
    name: "✦ EXT9 — MR Turbo Modificada",
    description: "Versão modificada do MR Turbo GT enviada por você, sem nenhuma alteração — arquivada como EXT9 e disponível para download direto. Isolada das demais extensões.",
    version: "9.0.1",
    status: "archived",
    tone: "lime",
    sourceDir: "extensions/ext-09/integrated/MR Turbo GT Mod",
    assets: {},
    manifest: {
      manifestVersion: 3,
      permissions: ["storage", "sidePanel", "scripting", "activeTab"],
      hasPopup: true,
      hasSidepanel: true,
      hasBackground: true,
      hasContentScripts: true,
    },
    builds: [],
    versions: [
      {
        version: "9.0.1",
        releasedAt: "2026-08-04",
        notes: "Versão arquivada.",
        changes: ["Modificação de terceiros", "Motor GT Base"],
      },
    ],
    createdAt: "2026-08-04",
    updatedAt: "2026-08-04",
  },
];