/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VersionsRouteImport } from './routes/versions'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LicensesRouteImport } from './routes/licenses'
import { Route as InstagramPreviewRouteImport } from './routes/instagram-preview'
import { Route as ExtensionsRouteImport } from './routes/extensions'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as DataDeletionRouteImport } from './routes/data-deletion'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as CompatibilityRouteImport } from './routes/compatibility'
import { Route as BuildCenterRouteImport } from './routes/build-center'
import { Route as BlocksRouteImport } from './routes/blocks'
import { Route as BlacklistRouteImport } from './routes/blacklist'
import { Route as BackendRouteImport } from './routes/backend'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as AnimationsRouteImport } from './routes/animations'
import { Route as ActivationsRouteImport } from './routes/activations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RuntimeIdRouteImport } from './routes/runtime.$id'
import { Route as PreviewIdRouteImport } from './routes/preview.$id'
import { Route as LiveIdRouteImport } from './routes/live.$id'
import { Route as ApiPublicOrbeTtsRouteImport } from './routes/api/public/orbe-tts'
import { Route as ApiPublicOrbeChatRouteImport } from './routes/api/public/orbe-chat'
import { Route as ApiPublicInstagramWebhookRouteImport } from './routes/api/public/instagram-webhook'
import { Route as ApiPublicInstagramStatusRouteImport } from './routes/api/public/instagram-status'
import { Route as ApiPublicInstagramPublishRouteImport } from './routes/api/public/instagram-publish'
import { Route as ApiPublicInstagramOauthStartRouteImport } from './routes/api/public/instagram-oauth-start'
import { Route as ApiPublicInstagramOauthCallbackRouteImport } from './routes/api/public/instagram-oauth-callback'
import { Route as ApiPublicInstagramMediaRouteImport } from './routes/api/public/instagram-media'
import { Route as ApiPublicInstagramGenerateRouteImport } from './routes/api/public/instagram-generate'
import { Route as ApiPublicExtVersionRouteImport } from './routes/api/public/ext-version'

const VersionsRoute = VersionsRouteImport.update({
  id: '/versions',
  path: '/versions',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LicensesRoute = LicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => rootRouteImport,
} as any)
const InstagramPreviewRoute = InstagramPreviewRouteImport.update({
  id: '/instagram-preview',
  path: '/instagram-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsRoute = ExtensionsRouteImport.update({
  id: '/extensions',
  path: '/extensions',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDeletionRoute = DataDeletionRouteImport.update({
  id: '/data-deletion',
  path: '/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const CompatibilityRoute = CompatibilityRouteImport.update({
  id: '/compatibility',
  path: '/compatibility',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildCenterRoute = BuildCenterRouteImport.update({
  id: '/build-center',
  path: '/build-center',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksRoute = BlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const BlacklistRoute = BlacklistRouteImport.update({
  id: '/blacklist',
  path: '/blacklist',
  getParentRoute: () => rootRouteImport,
} as any)
const BackendRoute = BackendRouteImport.update({
  id: '/backend',
  path: '/backend',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimationsRoute = AnimationsRouteImport.update({
  id: '/animations',
  path: '/animations',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivationsRoute = ActivationsRouteImport.update({
  id: '/activations',
  path: '/activations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimeIdRoute = RuntimeIdRouteImport.update({
  id: '/runtime/$id',
  path: '/runtime/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewIdRoute = PreviewIdRouteImport.update({
  id: '/preview/$id',
  path: '/preview/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveIdRoute = LiveIdRouteImport.update({
  id: '/live/$id',
  path: '/live/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOrbeTtsRoute = ApiPublicOrbeTtsRouteImport.update({
  id: '/api/public/orbe-tts',
  path: '/api/public/orbe-tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOrbeChatRoute = ApiPublicOrbeChatRouteImport.update({
  id: '/api/public/orbe-chat',
  path: '/api/public/orbe-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInstagramWebhookRoute =
  ApiPublicInstagramWebhookRouteImport.update({
    id: '/api/public/instagram-webhook',
    path: '/api/public/instagram-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInstagramStatusRoute =
  ApiPublicInstagramStatusRouteImport.update({
    id: '/api/public/instagram-status',
    path: '/api/public/instagram-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInstagramPublishRoute =
  ApiPublicInstagramPublishRouteImport.update({
    id: '/api/public/instagram-publish',
    path: '/api/public/instagram-publish',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInstagramOauthStartRoute =
  ApiPublicInstagramOauthStartRouteImport.update({
    id: '/api/public/instagram-oauth-start',
    path: '/api/public/instagram-oauth-start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInstagramOauthCallbackRoute =
  ApiPublicInstagramOauthCallbackRouteImport.update({
    id: '/api/public/instagram-oauth-callback',
    path: '/api/public/instagram-oauth-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInstagramMediaRoute = ApiPublicInstagramMediaRouteImport.update({
  id: '/api/public/instagram-media',
  path: '/api/public/instagram-media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInstagramGenerateRoute =
  ApiPublicInstagramGenerateRouteImport.update({
    id: '/api/public/instagram-generate',
    path: '/api/public/instagram-generate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExtVersionRoute = ApiPublicExtVersionRouteImport.update({
  id: '/api/public/ext-version',
  path: '/api/public/ext-version',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activations': typeof ActivationsRoute
  '/animations': typeof AnimationsRoute
  '/api-docs': typeof ApiDocsRoute
  '/assets': typeof AssetsRoute
  '/backend': typeof BackendRoute
  '/blacklist': typeof BlacklistRoute
  '/blocks': typeof BlocksRoute
  '/build-center': typeof BuildCenterRoute
  '/compatibility': typeof CompatibilityRoute
  '/components': typeof ComponentsRoute
  '/customers': typeof CustomersRoute
  '/data-deletion': typeof DataDeletionRoute
  '/devices': typeof DevicesRoute
  '/downloads': typeof DownloadsRoute
  '/editor': typeof EditorRoute
  '/extensions': typeof ExtensionsRoute
  '/instagram-preview': typeof InstagramPreviewRoute
  '/licenses': typeof LicensesRoute
  '/logs': typeof LogsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/prompts': typeof PromptsRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tools': typeof ToolsRoute
  '/versions': typeof VersionsRoute
  '/live/$id': typeof LiveIdRoute
  '/preview/$id': typeof PreviewIdRoute
  '/runtime/$id': typeof RuntimeIdRoute
  '/api/public/ext-version': typeof ApiPublicExtVersionRoute
  '/api/public/instagram-generate': typeof ApiPublicInstagramGenerateRoute
  '/api/public/instagram-media': typeof ApiPublicInstagramMediaRoute
  '/api/public/instagram-oauth-callback': typeof ApiPublicInstagramOauthCallbackRoute
  '/api/public/instagram-oauth-start': typeof ApiPublicInstagramOauthStartRoute
  '/api/public/instagram-publish': typeof ApiPublicInstagramPublishRoute
  '/api/public/instagram-status': typeof ApiPublicInstagramStatusRoute
  '/api/public/instagram-webhook': typeof ApiPublicInstagramWebhookRoute
  '/api/public/orbe-chat': typeof ApiPublicOrbeChatRoute
  '/api/public/orbe-tts': typeof ApiPublicOrbeTtsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activations': typeof ActivationsRoute
  '/animations': typeof AnimationsRoute
  '/api-docs': typeof ApiDocsRoute
  '/assets': typeof AssetsRoute
  '/backend': typeof BackendRoute
  '/blacklist': typeof BlacklistRoute
  '/blocks': typeof BlocksRoute
  '/build-center': typeof BuildCenterRoute
  '/compatibility': typeof CompatibilityRoute
  '/components': typeof ComponentsRoute
  '/customers': typeof CustomersRoute
  '/data-deletion': typeof DataDeletionRoute
  '/devices': typeof DevicesRoute
  '/downloads': typeof DownloadsRoute
  '/editor': typeof EditorRoute
  '/extensions': typeof ExtensionsRoute
  '/instagram-preview': typeof InstagramPreviewRoute
  '/licenses': typeof LicensesRoute
  '/logs': typeof LogsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/prompts': typeof PromptsRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tools': typeof ToolsRoute
  '/versions': typeof VersionsRoute
  '/live/$id': typeof LiveIdRoute
  '/preview/$id': typeof PreviewIdRoute
  '/runtime/$id': typeof RuntimeIdRoute
  '/api/public/ext-version': typeof ApiPublicExtVersionRoute
  '/api/public/instagram-generate': typeof ApiPublicInstagramGenerateRoute
  '/api/public/instagram-media': typeof ApiPublicInstagramMediaRoute
  '/api/public/instagram-oauth-callback': typeof ApiPublicInstagramOauthCallbackRoute
  '/api/public/instagram-oauth-start': typeof ApiPublicInstagramOauthStartRoute
  '/api/public/instagram-publish': typeof ApiPublicInstagramPublishRoute
  '/api/public/instagram-status': typeof ApiPublicInstagramStatusRoute
  '/api/public/instagram-webhook': typeof ApiPublicInstagramWebhookRoute
  '/api/public/orbe-chat': typeof ApiPublicOrbeChatRoute
  '/api/public/orbe-tts': typeof ApiPublicOrbeTtsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activations': typeof ActivationsRoute
  '/animations': typeof AnimationsRoute
  '/api-docs': typeof ApiDocsRoute
  '/assets': typeof AssetsRoute
  '/backend': typeof BackendRoute
  '/blacklist': typeof BlacklistRoute
  '/blocks': typeof BlocksRoute
  '/build-center': typeof BuildCenterRoute
  '/compatibility': typeof CompatibilityRoute
  '/components': typeof ComponentsRoute
  '/customers': typeof CustomersRoute
  '/data-deletion': typeof DataDeletionRoute
  '/devices': typeof DevicesRoute
  '/downloads': typeof DownloadsRoute
  '/editor': typeof EditorRoute
  '/extensions': typeof ExtensionsRoute
  '/instagram-preview': typeof InstagramPreviewRoute
  '/licenses': typeof LicensesRoute
  '/logs': typeof LogsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/prompts': typeof PromptsRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tools': typeof ToolsRoute
  '/versions': typeof VersionsRoute
  '/live/$id': typeof LiveIdRoute
  '/preview/$id': typeof PreviewIdRoute
  '/runtime/$id': typeof RuntimeIdRoute
  '/api/public/ext-version': typeof ApiPublicExtVersionRoute
  '/api/public/instagram-generate': typeof ApiPublicInstagramGenerateRoute
  '/api/public/instagram-media': typeof ApiPublicInstagramMediaRoute
  '/api/public/instagram-oauth-callback': typeof ApiPublicInstagramOauthCallbackRoute
  '/api/public/instagram-oauth-start': typeof ApiPublicInstagramOauthStartRoute
  '/api/public/instagram-publish': typeof ApiPublicInstagramPublishRoute
  '/api/public/instagram-status': typeof ApiPublicInstagramStatusRoute
  '/api/public/instagram-webhook': typeof ApiPublicInstagramWebhookRoute
  '/api/public/orbe-chat': typeof ApiPublicOrbeChatRoute
  '/api/public/orbe-tts': typeof ApiPublicOrbeTtsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activations'
    | '/animations'
    | '/api-docs'
    | '/assets'
    | '/backend'
    | '/blacklist'
    | '/blocks'
    | '/build-center'
    | '/compatibility'
    | '/components'
    | '/customers'
    | '/data-deletion'
    | '/devices'
    | '/downloads'
    | '/editor'
    | '/extensions'
    | '/instagram-preview'
    | '/licenses'
    | '/logs'
    | '/privacy-policy'
    | '/products'
    | '/profile'
    | '/prompts'
    | '/security'
    | '/settings'
    | '/support'
    | '/terms-of-service'
    | '/tools'
    | '/versions'
    | '/live/$id'
    | '/preview/$id'
    | '/runtime/$id'
    | '/api/public/ext-version'
    | '/api/public/instagram-generate'
    | '/api/public/instagram-media'
    | '/api/public/instagram-oauth-callback'
    | '/api/public/instagram-oauth-start'
    | '/api/public/instagram-publish'
    | '/api/public/instagram-status'
    | '/api/public/instagram-webhook'
    | '/api/public/orbe-chat'
    | '/api/public/orbe-tts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activations'
    | '/animations'
    | '/api-docs'
    | '/assets'
    | '/backend'
    | '/blacklist'
    | '/blocks'
    | '/build-center'
    | '/compatibility'
    | '/components'
    | '/customers'
    | '/data-deletion'
    | '/devices'
    | '/downloads'
    | '/editor'
    | '/extensions'
    | '/instagram-preview'
    | '/licenses'
    | '/logs'
    | '/privacy-policy'
    | '/products'
    | '/profile'
    | '/prompts'
    | '/security'
    | '/settings'
    | '/support'
    | '/terms-of-service'
    | '/tools'
    | '/versions'
    | '/live/$id'
    | '/preview/$id'
    | '/runtime/$id'
    | '/api/public/ext-version'
    | '/api/public/instagram-generate'
    | '/api/public/instagram-media'
    | '/api/public/instagram-oauth-callback'
    | '/api/public/instagram-oauth-start'
    | '/api/public/instagram-publish'
    | '/api/public/instagram-status'
    | '/api/public/instagram-webhook'
    | '/api/public/orbe-chat'
    | '/api/public/orbe-tts'
  id:
    | '__root__'
    | '/'
    | '/activations'
    | '/animations'
    | '/api-docs'
    | '/assets'
    | '/backend'
    | '/blacklist'
    | '/blocks'
    | '/build-center'
    | '/compatibility'
    | '/components'
    | '/customers'
    | '/data-deletion'
    | '/devices'
    | '/downloads'
    | '/editor'
    | '/extensions'
    | '/instagram-preview'
    | '/licenses'
    | '/logs'
    | '/privacy-policy'
    | '/products'
    | '/profile'
    | '/prompts'
    | '/security'
    | '/settings'
    | '/support'
    | '/terms-of-service'
    | '/tools'
    | '/versions'
    | '/live/$id'
    | '/preview/$id'
    | '/runtime/$id'
    | '/api/public/ext-version'
    | '/api/public/instagram-generate'
    | '/api/public/instagram-media'
    | '/api/public/instagram-oauth-callback'
    | '/api/public/instagram-oauth-start'
    | '/api/public/instagram-publish'
    | '/api/public/instagram-status'
    | '/api/public/instagram-webhook'
    | '/api/public/orbe-chat'
    | '/api/public/orbe-tts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivationsRoute: typeof ActivationsRoute
  AnimationsRoute: typeof AnimationsRoute
  ApiDocsRoute: typeof ApiDocsRoute
  AssetsRoute: typeof AssetsRoute
  BackendRoute: typeof BackendRoute
  BlacklistRoute: typeof BlacklistRoute
  BlocksRoute: typeof BlocksRoute
  BuildCenterRoute: typeof BuildCenterRoute
  CompatibilityRoute: typeof CompatibilityRoute
  ComponentsRoute: typeof ComponentsRoute
  CustomersRoute: typeof CustomersRoute
  DataDeletionRoute: typeof DataDeletionRoute
  DevicesRoute: typeof DevicesRoute
  DownloadsRoute: typeof DownloadsRoute
  EditorRoute: typeof EditorRoute
  ExtensionsRoute: typeof ExtensionsRoute
  InstagramPreviewRoute: typeof InstagramPreviewRoute
  LicensesRoute: typeof LicensesRoute
  LogsRoute: typeof LogsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProductsRoute: typeof ProductsRoute
  ProfileRoute: typeof ProfileRoute
  PromptsRoute: typeof PromptsRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  ToolsRoute: typeof ToolsRoute
  VersionsRoute: typeof VersionsRoute
  LiveIdRoute: typeof LiveIdRoute
  PreviewIdRoute: typeof PreviewIdRoute
  RuntimeIdRoute: typeof RuntimeIdRoute
  ApiPublicExtVersionRoute: typeof ApiPublicExtVersionRoute
  ApiPublicInstagramGenerateRoute: typeof ApiPublicInstagramGenerateRoute
  ApiPublicInstagramMediaRoute: typeof ApiPublicInstagramMediaRoute
  ApiPublicInstagramOauthCallbackRoute: typeof ApiPublicInstagramOauthCallbackRoute
  ApiPublicInstagramOauthStartRoute: typeof ApiPublicInstagramOauthStartRoute
  ApiPublicInstagramPublishRoute: typeof ApiPublicInstagramPublishRoute
  ApiPublicInstagramStatusRoute: typeof ApiPublicInstagramStatusRoute
  ApiPublicInstagramWebhookRoute: typeof ApiPublicInstagramWebhookRoute
  ApiPublicOrbeChatRoute: typeof ApiPublicOrbeChatRoute
  ApiPublicOrbeTtsRoute: typeof ApiPublicOrbeTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/versions': {
      id: '/versions'
      path: '/versions'
      fullPath: '/versions'
      preLoaderRoute: typeof VersionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licenses': {
      id: '/licenses'
      path: '/licenses'
      fullPath: '/licenses'
      preLoaderRoute: typeof LicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram-preview': {
      id: '/instagram-preview'
      path: '/instagram-preview'
      fullPath: '/instagram-preview'
      preLoaderRoute: typeof InstagramPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions': {
      id: '/extensions'
      path: '/extensions'
      fullPath: '/extensions'
      preLoaderRoute: typeof ExtensionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-deletion': {
      id: '/data-deletion'
      path: '/data-deletion'
      fullPath: '/data-deletion'
      preLoaderRoute: typeof DataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compatibility': {
      id: '/compatibility'
      path: '/compatibility'
      fullPath: '/compatibility'
      preLoaderRoute: typeof CompatibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-center': {
      id: '/build-center'
      path: '/build-center'
      fullPath: '/build-center'
      preLoaderRoute: typeof BuildCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks': {
      id: '/blocks'
      path: '/blocks'
      fullPath: '/blocks'
      preLoaderRoute: typeof BlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blacklist': {
      id: '/blacklist'
      path: '/blacklist'
      fullPath: '/blacklist'
      preLoaderRoute: typeof BlacklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend': {
      id: '/backend'
      path: '/backend'
      fullPath: '/backend'
      preLoaderRoute: typeof BackendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animations': {
      id: '/animations'
      path: '/animations'
      fullPath: '/animations'
      preLoaderRoute: typeof AnimationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activations': {
      id: '/activations'
      path: '/activations'
      fullPath: '/activations'
      preLoaderRoute: typeof ActivationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtime/$id': {
      id: '/runtime/$id'
      path: '/runtime/$id'
      fullPath: '/runtime/$id'
      preLoaderRoute: typeof RuntimeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$id': {
      id: '/preview/$id'
      path: '/preview/$id'
      fullPath: '/preview/$id'
      preLoaderRoute: typeof PreviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$id': {
      id: '/live/$id'
      path: '/live/$id'
      fullPath: '/live/$id'
      preLoaderRoute: typeof LiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/orbe-tts': {
      id: '/api/public/orbe-tts'
      path: '/api/public/orbe-tts'
      fullPath: '/api/public/orbe-tts'
      preLoaderRoute: typeof ApiPublicOrbeTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/orbe-chat': {
      id: '/api/public/orbe-chat'
      path: '/api/public/orbe-chat'
      fullPath: '/api/public/orbe-chat'
      preLoaderRoute: typeof ApiPublicOrbeChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/instagram-webhook': {
      id: '/api/public/instagram-webhook'
      path: '/api/public/instagram-webhook'
      fullPath: '/api/public/instagram-webhook'
      preLoaderRoute: typeof ApiPublicInstagramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/instagram-status': {
      id: '/api/public/instagram-status'
      path: '/api/public/instagram-status'
      fullPath: '/api/public/instagram-status'
      preLoaderRoute: typeof ApiPublicInstagramStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/instagram-publish': {
      id: '/api/public/instagram-publish'
      path: '/api/public/instagram-publish'
      fullPath: '/api/public/instagram-publish'
      preLoaderRoute: typeof ApiPublicInstagramPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/instagram-oauth-start': {
      id: '/api/public/instagram-oauth-start'
      path: '/api/public/instagram-oauth-start'
      fullPath: '/api/public/instagram-oauth-start'
      preLoaderRoute: typeof ApiPublicInstagramOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/instagram-oauth-callback': {
      id: '/api/public/instagram-oauth-callback'
      path: '/api/public/instagram-oauth-callback'
      fullPath: '/api/public/instagram-oauth-callback'
      preLoaderRoute: typeof ApiPublicInstagramOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/instagram-media': {
      id: '/api/public/instagram-media'
      path: '/api/public/instagram-media'
      fullPath: '/api/public/instagram-media'
      preLoaderRoute: typeof ApiPublicInstagramMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/instagram-generate': {
      id: '/api/public/instagram-generate'
      path: '/api/public/instagram-generate'
      fullPath: '/api/public/instagram-generate'
      preLoaderRoute: typeof ApiPublicInstagramGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ext-version': {
      id: '/api/public/ext-version'
      path: '/api/public/ext-version'
      fullPath: '/api/public/ext-version'
      preLoaderRoute: typeof ApiPublicExtVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivationsRoute: ActivationsRoute,
  AnimationsRoute: AnimationsRoute,
  ApiDocsRoute: ApiDocsRoute,
  AssetsRoute: AssetsRoute,
  BackendRoute: BackendRoute,
  BlacklistRoute: BlacklistRoute,
  BlocksRoute: BlocksRoute,
  BuildCenterRoute: BuildCenterRoute,
  CompatibilityRoute: CompatibilityRoute,
  ComponentsRoute: ComponentsRoute,
  CustomersRoute: CustomersRoute,
  DataDeletionRoute: DataDeletionRoute,
  DevicesRoute: DevicesRoute,
  DownloadsRoute: DownloadsRoute,
  EditorRoute: EditorRoute,
  ExtensionsRoute: ExtensionsRoute,
  InstagramPreviewRoute: InstagramPreviewRoute,
  LicensesRoute: LicensesRoute,
  LogsRoute: LogsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProductsRoute: ProductsRoute,
  ProfileRoute: ProfileRoute,
  PromptsRoute: PromptsRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  ToolsRoute: ToolsRoute,
  VersionsRoute: VersionsRoute,
  LiveIdRoute: LiveIdRoute,
  PreviewIdRoute: PreviewIdRoute,
  RuntimeIdRoute: RuntimeIdRoute,
  ApiPublicExtVersionRoute: ApiPublicExtVersionRoute,
  ApiPublicInstagramGenerateRoute: ApiPublicInstagramGenerateRoute,
  ApiPublicInstagramMediaRoute: ApiPublicInstagramMediaRoute,
  ApiPublicInstagramOauthCallbackRoute: ApiPublicInstagramOauthCallbackRoute,
  ApiPublicInstagramOauthStartRoute: ApiPublicInstagramOauthStartRoute,
  ApiPublicInstagramPublishRoute: ApiPublicInstagramPublishRoute,
  ApiPublicInstagramStatusRoute: ApiPublicInstagramStatusRoute,
  ApiPublicInstagramWebhookRoute: ApiPublicInstagramWebhookRoute,
  ApiPublicOrbeChatRoute: ApiPublicOrbeChatRoute,
  ApiPublicOrbeTtsRoute: ApiPublicOrbeTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
